language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.8.0
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - 'yarn global add lerna'
script:
  - yarn build-server
  - cd frontend/applications/nominations && yarn build
